### ISSUE TITLE
Bugs for v1.2

### ISSUE THREAD

**Issue by hans555** [AY1920S2-CS2103T-F11-4/main#118]
**Bugs** (as of 23 March 2020)

**Cookbook commands:**

- [x] `cookbook add n/RECIPE d/DESCRIPTION` -> works as intended
- [x] `cookbook remove [INDEX]` -> error message not consistent when index <= 0 and index > size of list (fixed in #122)
- [x] `cookbook view [INDEX]` -> error message not consistent (same as above), need to display steplist and ingredient list properly (fixed in #122)

**Recipe commands:**

- [x] `recipe [INDEX] add...` -> error message not consistent when index <= 0 and index > size of list (fixed in #122)
- [x] `recipe [INDEX] add/remove x/STEP_INDEX s/STEP` -> works as intended, error message not consistent for index (fixed in #122)
- [x] `recipe [INDEX] add i/INGREDIENT q/QUANTITY` -> cannot add same ingredient causing duplicated ingredient exception (fixed in @gohkh's PR)
- [x] `recipe [INDEX] remove i/INGREDIENT q/QUANTITY`
- [x] `recipe [INDEX] add t/TAG` -> works as intended
- [x] `recipe [INDEX] remove t/TAG` -> works as intended

**Inventory commands:**

- [x] `inventory add` -> showing recipeAddCommand.Message usage, need to have its own message usage
- [x] `inventory add i/ingredient` -> shows java.util.NoSuchElementException: No value present.
- [x] `inventory add i/ingredient q/quantity` -> works as intended
- [x] `inventory remove i/ingredient` -> shows java.util.NoSuchElementException: No value present.
- [x] `inventory remove i/ingredient q/quantity` -> works as intended but it accept a quantity that is larger than the current inventory

**Cart commands:**

- [x] `cart clear` -> does not work
- [x] `cart add i/ingredient q/quantity` -> works as intended
- [x] `cart remove i/ingredient q/quantity` -> works as intended but it accept a quantity that is larger than the current inventory

 
**Others:** _(Not implemented yet)_ 
- [x] Display step list and ingredient list as proper list in result window
- [x] Make parser exception more consistent across all commands
- [x] cookbook recipes does not save after exiting the application

**Comment by teo-jun-xiong** [comment]
For the parser exceptions, would making subclasses of it be more feasible? E.g. InventoryAddIngredientListIndexException etc.?

**Comment by hans555** [comment]
> For the parser exceptions, would making subclasses of it be more feasible? E.g. InventoryAddIngredientListIndexException etc.?

I think no need to be so exact. the issue i got when i was testing is that the parser exceptions are not consistent meaning like if i type "cookbook add" vs "recipe add" . They should give similar kind of parser exception message. For now it is different

**Comment by teo-jun-xiong** [comment]
> `recipe [INDEX] add i/INGREDIENT q/QUANTITY` -> cannot add same ingredient causing duplicated ingredient exception

Are we allowing users to add the same ingredients to a recipe (i.e. increasing the quantity required)?
